apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-staging
  namespace: helloworld  # Adjust this to the namespace where your service is running
spec:
  acme:
    # The ACME server URL for Let's Encrypt production environment
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    # Email address used for ACME registration
    email: benslamasouheil@gmail.com
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-staging
    # Configure the HTTP-01 challenge provider
    solvers:
    - http01:
        ingress:
          class: nginx  # This should match your Ingress Controller, change if using something other than nginx
